### ISSUE TITLE
How to Customize the android operating system 

### ISSUE THREAD

**Issue by MuneshThakur** [OfficeDev/O365-Android-Start#2]
Hello Sir 
                   can you tell me how to customize the android operating system for new hardware and where , i can add my splash and my company name. and give me some info about , how to write android source code on Linux Kernal.

Thanks & Regards
Munesh parmar

**Comment by davechmsft** [comment]
Hi Munesh,

This GitHub repository is for using the O365-Android-Start code sample to learn how to connect your Android app to Office 365 services. Your question would be better answered on a forum specific to Android development.

Thanks,
David Chesnut
