### ISSUE TITLE
Hello Community 

### ISSUE THREAD

**Issue by MuneshThakur** [OfficeDev/O365-Android-Start#3]
Hi sir
           I am using android tablet . and in this device sleeping time only 15,10,5  Minute .I want to set sleeping time according to my android application .can you suggest me how to solve it.
thanks & regard 
Munesh parmar

**Comment by davechmsft** [comment]
Hi Munesh,

Thanks for the question, but this repo is not the place to ask general Android questions. I suggest trying a dedicated Android community forum, such as the one at stackoverflow (http://stackoverflow.com/questions/tagged/android). Someone there will likely be able to help you.

Thanks,
David Chesnut
